//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RestaurantFacultyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        
        public int ID { get; set; }
        [Display(Name = "Name")]
        public string NAME { get; set; }
        [Display(Name = "Surname")]
        public string SURNAME { get; set; }
    }
}
