//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFacultyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend_rating
    {
        public int ID { get; set; }
        public int CUS_ID { get; set; }
        public int COUNT { get; set; }
        public int SUM { get; set; }
    }
}
