//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantFacultyApplication
{
    using System;
    using System.Collections.Generic;

    public partial class Meal
    {
        public int ID { get; set; }
        [Display(Name = "Restaurant")]
        public int RES_ID { get; set; }
        [Display(Name = "Name")]
        public string NAME { get; set; }
        [Display(Name = "Description")]
        public string DECRIPTION { get; set; }
        [Display(Name = "Price")]
        public float PRICE { get; set; }
    }
}
