//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFacultyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth2_account
    {
        public int OA_ID { get; set; }
        public int ID { get; set; }
        public string OA_SOCIAL_NETWORK { get; set; }
        public string OD_USER_ID { get; set; }
    }
}
