//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RestaurantFacultyApplication
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        [Display(Name = "Id")]
        public int ID { get; set; }
        [Display(Name = "Restaurant")]
        public Nullable<int> RES_ID { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }
        [Display(Name = "Role")]
        public string ROLE { get; set; }
        [Display(Name = "Activated")]
        public Nullable<bool> ACTIVATED { get; set; }
    }
}
